name: Solar System Workflow

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'

env:
    MONGO_URI: 'mongodb+srv://superUser:${{ secrets.MONGO_PASSWORD }}@cluster0.egdm53l.mongodb.net/?appName=Cluster0'
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v7

            - name: Setup node version - 24
              uses: actions/setup-node@v7
              with:
                node-version: 24
            - name: Instaling Dependencies
              run: npm install

            - name: Unit Testing
              run: npm test --reporter spec
